base: &base
  adapter: postgresql
  encoding: unicode
  pool: 5
  host: localhost

development:
  database: api_test_development
  password: 
  username: 'marcuslopes'
  <<: *base

test:
  database: api_test_test
  password: 
  username: 'marcuslopes'
  <<: *base  

production:
  database: api_test_production
  password: 
  username: 'marcuslopes'
  <<: *base  
